"""SupportPilot AI — Mock Provider for Development

Returns realistic-looking responses without needing any API keys.
Uses hash-based embeddings so vector search actually works in dev.
"""

from __future__ import annotations

import hashlib
import math
import random
from collections.abc import AsyncGenerator

from app.ai.providers.base import (
    AIProvider,
    ChatRequest,
    ChatResponse,
    EmbeddingRequest,
    EmbeddingResponse,
)


_RESPONSES = [
    "I understand your question. Based on the knowledge base, here's what I can tell you: {query}",
    "Great question! Let me look into this. From the available information, I can share that {query}",
    "Thanks for asking. The relevant documentation suggests that {query}",
    "That's a common question. According to the knowledge base, {query}",
    "Let me search the knowledge base for this. I found that {query}",
]

_RESPONSE_PARAGRAPHS = [
    "This is a simulated AI response for development purposes. In production, this would be generated by a real AI model using your configured provider.",
    "The knowledge base contains relevant information about this topic. I've retrieved the most relevant chunks to provide you with an accurate answer.",
    "Based on the available documentation, here are the key points you should consider. Remember that this is a mock response and should be replaced with actual AI-generated content in production.",
    "If you need more specific information, please provide additional context or check the knowledge base for more detailed documentation.",
]

_EMBEDDING_DIM = 384


class MockProvider(AIProvider):
    """Mock provider for development — no API keys required."""

    _seed: int = 42

    def __init__(self) -> None:
        self._rng = random.Random(self._seed)

    @property
    def provider_name(self) -> str:
        return "mock"

    def get_default_model(self) -> str:
        return "mock-model"

    def get_embedding_model(self) -> str:
        return "mock-embedding"

    def _build_response(self, query: str) -> str:
        rng = random.Random(hashlib.md5(query.encode()).hexdigest())
        template = rng.choice(_RESPONSES)
        response = template.format(query=query[:80])
        paragraphs = rng.sample(_RESPONSE_PARAGRAPHS, rng.randint(1, 3))
        return response + "\n\n" + "\n\n".join(paragraphs)

    async def chat_complete(self, request: ChatRequest) -> ChatResponse:
        last_msg = request.messages[-1].content if request.messages else ""
        content = self._build_response(last_msg)
        return ChatResponse(
            content=content,
            model=self.get_default_model(),
            usage={"prompt_tokens": 50, "completion_tokens": 100, "total_tokens": 150},
            finish_reason="stop",
        )

    async def chat_complete_stream(
        self, request: ChatRequest
    ) -> AsyncGenerator[str, None]:
        response = await self.chat_complete(request)
        content = response.content

        chunk_size = random.randint(3, 8)
        i = 0
        while i < len(content):
            end = min(i + chunk_size, len(content))
            yield content[i:end]
            i = end

    async def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        embeddings = []
        for text in request.texts:
            vector = self._hash_to_vector(text)
            embeddings.append(vector)
        return EmbeddingResponse(
            embeddings=embeddings,
            model=self.get_embedding_model(),
            usage={"prompt_tokens": len(request.texts) * 10, "total_tokens": len(request.texts) * 10},
        )

    def _hash_to_vector(self, text: str) -> list[float]:
        h = hashlib.sha256(text.encode()).hexdigest()
        rng = random.Random(h)
        vec = [rng.uniform(-1.0, 1.0) for _ in range(_EMBEDDING_DIM)]
        norm = math.sqrt(sum(x * x for x in vec))
        return [x / norm for x in vec]
